services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'


    volumes:
      - postgres_data:/var/lib/postgresql/data

  # usuario-ms:
  #   build: .

  #   environment:
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}

  #   ports:
  #     - "8081:8081"

  #   depends_on:
  #     - postgres

volumes:
  postgres_data: